drivers: input: gpio: Add missing `int` in variable declaration
drivers/input/keyboard/gpio_keys.c:385:9: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
        static gs_old_state;
        ~~~~~~ ^
        int

Change-Id: Iaaf1c8a294451e5a6e7cf77a403f6860c15ef701